name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3 

      - name: Установка SSH-ключа
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Деплой на сервер
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ./songchords-api
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d --remove-orphans
          EOF